plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.143'
}

group = project.mod_group
version = project.mod_version
base { archivesName = project.mod_name }

java {
    toolchain { languageVersion = JavaLanguageVersion.of(25) }
}

repositories {
    mavenCentral()
}

neoForge {
    version = project.neoforge_version

    runs {
        client {
            client()
            gameDirectory = file('run')
        }
    }

    mods {
        mineniteclient {
            sourceSet sourceSets.main
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

processResources {
    inputs.property 'version', project.version
    filesMatching('META-INF/neoforge.mods.toml') {
        expand version: project.version
    }
}
